### ISSUE TITLE
Relies on Windows registry

### ISSUE THREAD

**Issue by alchzh** [benjibobs/Steam-Shutdown#5]
wouldn't it be better (and more cross platform) to monitor HDD write and see if steam is doing anything?

**Comment by benjibobs** [comment]
Yes, however bear in mind this is written in C# (.NET) which is designed for Windows. I may make a new branch where I work on a version which could be used with mono or wine and would therefore be usable on different platforms, but at the moment it is not a priority.

If I were to make a new branch, I think this would be how I would make it compatible, that or network usage as suggested in the Reddit thread!

**Comment by alchzh** [comment]
definitely works in mono excluding registry checking and maybe shutdown functions

**Comment by benjibobs** [comment]
I'll look into it then

**Comment by benjibobs** [comment]
[Progress](https://github.com/benjibobs/Steam-Shutdown/tree/mono)

**Comment by benjibobs** [comment]
Please test at link above. Will not merge with master until you confirm if this works!

**Comment by alchzh** [comment]
hmm, at the office with a windows machine atm so can't test, however noticed a few things, commented the diff

EDIT: all these ifMono() and ifUNIX() things seem unnecessary... why not just put it into a seperate C# file or something lol

and I'm pretty sure you can change the steam install directory, will have to check that when home

**Comment by benjibobs** [comment]
> EDIT: all these ifMono() and ifUNIX() things seem unnecessary... why not just put it into a seperate C# file or something lol

I felt it would be easier to keep it in the same class because even if I use a separate file most of the contents will be the same except for the stuff in the if statements. Am open to changing that if convinced!

> and I'm pretty sure you can change the steam install directory, will have to check that when home

Yeh, that's why I added selectLibrary(), it asks for your library file location and you can set a custom one or just press enter for the default (the isUNIX() is needed for the shutdown commands, but I added it in stuff like that too because you can run mono on Windows, and it makes sense giving two people on the same platform a different experience based on if they use mono or not)
I think I may just make the selectLibrary() universal and detect the default based on the OS, as it could be a useful feature.

---

hmm, at the office with a windows machine atm so can't test, however noticed a few things, commented the diff

EDIT: all these ifMono() and ifUNIX() things seem unnecessary... why not just put it into a seperate C# file or something lol

and I'm pretty sure you can change the steam install directory, will have to check that when home

##

**Comment by benjibobs** [comment]
Testing locally. Scrapping Windows library select due to the nature of the registry checks (it is unneeded)
